#ifndef APPENUMS_H
#define APPENUMS_H

#include <QObject>

class AppEnums : public QObject
{
    Q_OBJECT
    Q_ENUMS( HMI_TEST_CASES )

public:

    enum HMI_TEST_CASES: int
    {
        HMI_CASE_LIKE_NEW_FEED = 0,
        HMI_CASE_ADD_CONFIRM_FRIEND,
        HMI_CASE_ADD_FRIEND_BY_UID,
        HMI_CASE_FOLLOW_PAGE,
        HMI_CASE_LIKE_PAGE,
        HMI_CASE_SHARE_PROFILE,

        HMI_CASE_SHARE_PAGE,
        HMI_CASE_GROUP_LIKE,
        HMI_CASE_GROUP_COMMENT,
        HMI_CASE_UP_PHOTO,
        HMI_CASE_SET_PHOTO_TO_AVT,
        HMI_CASE_UPDATE_INFO
    };

    enum E_EXCUTE_STEPS: int
    {
        E_EXCUTE_CHANGE_INFO = 0,
        E_EXCUTE_REG_GMAIL,
        E_EXCUTE_REG_FACBOOK,
    };

    enum E_FBLITE_SCREEN_ID: int
    {
        E_FBLITE_SCREEN_ID_LOGIN = 0,
        E_FBLITE_SCREEN_ID_JOIN_FB,
        E_FBLITE_SCREEN_ID_ENTER_NAME,
        E_FBLITE_SCREEN_ID_ENTER_MOBILE_NUM,
        E_FBLITE_SCREEN_ID_ENTER_EMAIL_ADDRESS,
        E_FBLITE_SCREEN_ID_ENTER_BIRTHDAY,
        E_FBLITE_SCREEN_ID_ENTER_GENDER,
        E_FBLITE_SCREEN_ID_ENTER_PASSWORD,
        E_FBLITE_SCREEN_ID_SAVE_LOGIN_INFO,
        E_FBLITE_SCREEN_ID_CONFIRM_EMAIL,
        E_FBLITE_SCREEN_ID_WELCOME_SCREEN,
        E_FBLITE_SCREEN_ID_ADD_PIC_PROFILE,
        E_FBLITE_SCREEN_ID_FIND_FRIENDS,
        E_FBLITE_SCREEN_ID_NEW_FEEDS,
        E_FBLITE_SCREEN_ID_CHECK_POINT,
        E_FBLITE_SCREEN_ID_UNKNOW
    };

    enum E_APP_ID: int
    {
        E_FACEBOOK_LITE = 0,
        E_GOOGLE_BACKUP_TRANSPORT,
        E_GOOGLE_PLUS,
        E_GOOGLE_SERVICE_FRAMEWORK,
        E_GOOGLE_PLAY_SERVICE,
        E_GOOGLE_PARTNER_SETUP,
        E_GOOGLE_CHROME,
        E_GOOGLE_ACCOUNT_MANAGER,
        E_LOCATION_SERVICES,
        E_GOOGLE_PLAY_STORE,
    };
};

#endif // APPENUMS_H
